network_name: "esnet"

elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.14
elasticsearch_hostname: es01
elasticsearch_conf_dir: /usr/share/elasticsearch

kibana_image: docker.elastic.co/kibana/kibana:7.14
kibana_hostname: ki01

log_driver: "json-file"
log_max_size: "10m"
log_max_file: "3"

elastic_password: "1qaz2wsx"
kibana_password: "1qaz2wsx"