- name: Create elastic search volume1
  docker_volume:
    name: esdata
    driver: local
- name: Create elastic search volume2
  docker_volume:
    name: esdata02
    driver: local

- name: Create elastic search volume3
  docker_volume:
    name: esdata03
    driver: local

- name: Create ssl docker
  docker_volume:
    name: certs
    driver: local  

- name: Start elastic search container (Master)
  docker_container:
    name: "es01"
    image: "{{ elasticsearch_image }}"

    env:
      cluster_name: "my-cluster"
      discovery.seed_hosts: "es02,es03"
      cluster.initial_master_nodes: "es01"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.license.self_generated.type: "trial"
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true" 
      xpack.security.http.ssl.key: "/usr/share/elasticsearch/config/certificates/es01/es01.key"
      xpack.security.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.http.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es01/es01.crt"
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: "certificate" 
      xpack.security.transport.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es01/es01.crt"
      xpack.security.transport.ssl.key: "/usr/share/elasticsearch/config/certificates/es01/es01.key"

    volumes:
    - "esdata:/usr/share/elasticsearch/data"
    ulimits:
    - nofile:65535:65535
    networks:
    - name: "{{ network_name }}"
    state: started
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"

- name: Start elastic search container (Data2)
  docker_container:
    name: "es02"
    image: "{{ elasticsearch_image }}"

    env:
      cluster_name: "my-cluster"
      discovery.seed_hosts: "es01,es03"
      cluster.initial_master_nodes: "es01"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.license.self_generated.type: "trial"
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true" 
      xpack.security.http.ssl.key: "/usr/share/elasticsearch/config/certificates/es02/es02.key"
      xpack.security.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.http.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es02/es02.crt"
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: "certificate" 
      xpack.security.transport.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es02/es02.crt"
      xpack.security.transport.ssl.key: "/usr/share/elasticsearch/config/certificates/es02/es02.key"
  

    volumes:
    - "esdata02:/usr/share/elasticsearch/data"
    ulimits:
    - nofile:65535:65535
    networks:
    - name: "{{ network_name }}"
    state: started
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"

- name: Start elastic search container (Data3)
  docker_container:
    name: "es03"
    image: "{{ elasticsearch_image }}"

    env:
      cluster_name: "my-cluster"
      discovery.seed_hosts: "es01,es02"
      cluster.initial_master_nodes: "es01"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.license.self_generated.type: "trial"
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "true" 
      xpack.security.http.ssl.key: "/usr/share/elasticsearch/config/certificates/es03/es03.key"
      xpack.security.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.http.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es03/es03.crt"
      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: "certificate" 
      xpack.security.transport.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
      xpack.security.transport.ssl.certificate: "/usr/share/elasticsearch/config/certificates/es03/es03.crt"
      xpack.security.transport.ssl.key: "/usr/share/elasticsearch/config/certificates/es03/es03.key"
  

    volumes:
    - "esdata03:/usr/share/elasticsearch/data"
    ulimits:
    - nofile:65535:65535
    networks:
    - name: "{{ network_name }}"
    state: started
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"
